development:
  adapter: postgresql
  encoding: unicode
  database: fresh-built_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: fresh-built_production
  pool: 5
  username: postgres
  password:
